# Generated by Django 5.2.6 on 2025-10-12 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version number (e.g., '1.0.0', '2.0.0')", max_length=50, unique=True)),
                ('content', models.TextField(help_text='Full text of the Terms of Service (lorem ipsum for now)')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tos_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the user accepted', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('tos_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='legal.termsofservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOS Acceptance',
                'verbose_name_plural': 'TOS Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('tos_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='legal.termsofservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOS Notification',
                'verbose_name_plural': 'TOS Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='termsofservice',
            index=models.Index(fields=['is_active'], name='legal_terms_is_acti_ddf9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofservice',
            index=models.Index(fields=['-created_at'], name='legal_terms_created_09902e_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofserviceacceptance',
            index=models.Index(fields=['user', '-accepted_at'], name='legal_terms_user_id_ae0cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofserviceacceptance',
            index=models.Index(fields=['tos_version'], name='legal_terms_tos_ver_20fe33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termsofserviceacceptance',
            unique_together={('user', 'tos_version')},
        ),
        migrations.AddIndex(
            model_name='termsofservicenotification',
            index=models.Index(fields=['user', 'tos_version'], name='legal_terms_user_id_212459_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofservicenotification',
            index=models.Index(fields=['status'], name='legal_terms_status_42deb6_idx'),
        ),
        migrations.AddIndex(
            model_name='termsofservicenotification',
            index=models.Index(fields=['-created_at'], name='legal_terms_created_6899b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termsofservicenotification',
            unique_together={('user', 'tos_version')},
        ),
    ]
