# Generated by Django 5.2.6 on 2025-10-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofservice',
            name='content',
        ),
    ]
