# Generated by Django 5.2.6 on 2025-10-12 08:54

from django.db import migrations


def remove_linkedin_oauth2_socialapp(apps, schema_editor):
    """
    Remove old linkedin_oauth2 SocialApp objects from database.

    LinkedIn has migrated from linkedin_oauth2 provider to OpenID Connect.
    The platform now uses settings-based configuration instead of database
    SocialApp objects for LinkedIn authentication.

    This migration removes any existing linkedin_oauth2 SocialApp objects
    to ensure the OpenID Connect configuration is used.
    """
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    # Find and delete all linkedin_oauth2 SocialApp objects
    linkedin_oauth2_apps = SocialApp.objects.filter(provider="linkedin_oauth2")
    count = linkedin_oauth2_apps.count()

    if count > 0:
        linkedin_oauth2_apps.delete()
        print(f"Removed {count} linkedin_oauth2 SocialApp object(s)")
    else:
        print("No linkedin_oauth2 SocialApp objects found (already clean)")


def restore_linkedin_oauth2_socialapp(apps, schema_editor):
    """
    Reverse migration - does nothing.

    We don't restore the old linkedin_oauth2 SocialApp objects because:
    1. LinkedIn no longer supports the old OAuth2 v2 API
    2. The platform now uses settings-based OpenID Connect configuration
    3. Restoring would break LinkedIn authentication

    If you need to roll back, you should:
    1. Update settings to use linkedin_oauth2 provider
    2. Manually create SocialApp objects if needed
    """
    print("Reverse migration: No action taken (old linkedin_oauth2 is deprecated)")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('socialaccount', '__latest__'),  # Ensure SocialApp model is available
    ]

    operations = [
        migrations.RunPython(
            remove_linkedin_oauth2_socialapp,
            reverse_code=restore_linkedin_oauth2_socialapp,
        ),
    ]
