# Generated by Django 5.2.6 on 2025-09-23 22:20

import django.core.validators
import django.db.models.deletion
import uuid
import wafer_space.projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('checking', 'Checking Manufacturability'), ('manufacturable', 'Manufacturable'), ('not_manufacturable', 'Not Manufacturable'), ('assigned', 'Assigned to Shuttle'), ('production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_manufacturable', models.BooleanField(blank=True, null=True)),
                ('manufacturability_errors', models.JSONField(blank=True, default=list)),
                ('check_completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturabilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('is_manufacturable', models.BooleanField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('processing_logs', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturability_check', to='projects.project')),
            ],
            options={
                'verbose_name': 'Manufacturability Check',
                'verbose_name_plural': 'Manufacturability Checks',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=wafer_space.projects.models.project_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'gds', 'gdsii', 'cif', 'pdf', 'png', 'jpg', 'svg'])])),
                ('file_type', models.CharField(choices=[('design', 'Design File'), ('docs', 'Documentation'), ('schematic', 'Schematic'), ('layout', 'Layout'), ('gerber', 'Gerber Files'), ('other', 'Other')], default='design', max_length=20)),
                ('url_source', models.URLField(blank=True, help_text='Original URL if file was fetched from remote source')),
                ('hash_md5', models.CharField(blank=True, max_length=32)),
                ('hash_sha1', models.CharField(blank=True, max_length=40)),
                ('hash_verified', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_40c3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'created_at'], name='projects_pr_status_7ee874_idx'),
        ),
    ]
