# Generated by Django 5.2.6 on 2025-09-24 23:41

import django.core.validators
import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='download_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='download_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='download_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Download Pending'), ('downloading', 'Downloading'), ('completed', 'Download Completed'), ('failed', 'Download Failed'), ('local', 'Local Upload')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='download_task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='expected_hash_md5',
            field=models.CharField(blank=True, help_text='MD5 hash provided by user for verification', max_length=32),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='expected_hash_sha1',
            field=models.CharField(blank=True, help_text='SHA1 hash provided by user for verification', max_length=40),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL to download the file from'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=wafer_space.projects.models.project_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'gds', 'gdsii', 'cif', 'pdf', 'png', 'jpg', 'svg'])]),
        ),
    ]
