# Generated by Django 5.2.6 on 2025-10-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_url_download_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='url_source',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this is the currently active file for the project'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp for download progress tracking', null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original URL submitted by user (before any rewriting)'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='The file that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='projects.projectfile'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='source_url',
            field=models.URLField(blank=True, help_text='Actual URL to download from (after URL rewriting if applicable)'),
        ),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project',), name='one_active_file_per_project'),
        ),
    ]
