# Generated by Django 5.2.6 on 2025-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_file_replacement_and_url_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Download Pending'), ('downloading', 'Downloading'), ('completed', 'Download Completed'), ('failed', 'Download Failed')], default='pending', max_length=20),
        ),
    ]
