# Generated by Django 5.2.6 on 2025-10-19 03:48

import django.core.validators
import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectfile_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='handler_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata from URL handler (e.g., which handler was used, handler-specific data)'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=wafer_space.projects.models.project_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gds', 'gdsii', 'gds2', 'oas', 'oasis', 'gz', 'zip', 'bz2', 'xz'])]),
        ),
    ]
