# Generated by Django 5.2.6 on 2025-10-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectfile_handler_metadata_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturabilitycheck',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
