# Generated by Django 5.2.6 on 2025-10-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_manufacturabilitycheck_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this checkpoint was recorded')),
                ('bytes_downloaded', models.BigIntegerField(help_text='Cumulative bytes downloaded at this checkpoint')),
                ('chunk_number', models.IntegerField(help_text='Sequential chunk number for ordering')),
                ('project_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='projects.projectfile')),
            ],
            options={
                'ordering': ['chunk_number'],
                'indexes': [models.Index(fields=['project_file', 'chunk_number'], name='projects_pr_project_51d27a_idx'), models.Index(fields=['project_file', 'timestamp'], name='projects_pr_project_06e03b_idx')],
            },
        ),
    ]
