# Generated by Django 5.2.6 on 2025-10-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectfilechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='auto_retry_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic retry for failed downloads'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='When the last automatic retry was attempted', null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of automatic retries before giving up'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, help_text='When the next automatic retry should be attempted (exponential backoff)', null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of automatic retries attempted'),
        ),
    ]
