# Generated by Django 5.2.6 on 2025-10-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectfile_auto_retry_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='task_started_at',
            field=models.DateTimeField(blank=True, help_text='When download task actually began execution', null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='worker_hostname',
            field=models.CharField(blank=True, help_text='Hostname of worker machine', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='worker_pid',
            field=models.IntegerField(blank=True, help_text='Process ID of Celery worker executing download', null=True),
        ),
    ]
