# Generated by Django 5.2.6 on 2025-10-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectfile_worker_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='worker_hostname',
            field=models.CharField(blank=True, default='', help_text='Hostname of worker machine', max_length=255),
        ),
    ]
