# Generated by Django 5.2.6 on 2025-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectfile_worker_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Download Pending'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Download Completed'), ('failed', 'Download Failed')], default='pending', max_length=20),
        ),
    ]
