# Generated by Django 5.2.6 on 2025-10-22 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectfile_queued_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submitted_file',
            field=models.ForeignKey(blank=True, help_text='The file that was submitted for manufacturing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_for_project', to='projects.projectfile'),
        ),
    ]
