# Generated by Django 5.2.6 on 2025-11-16 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_project_submitted_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Docker image used (e.g., ghcr.io/wafer-space/gf180mcu-precheck:latest)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_image_digest",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 digest of Docker image for reproducibility",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                help_text="Last activity timestamp for progress tracking",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="precheck_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="gf180mcu-precheck version/commit hash",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="rerun_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this check was re-run (e.g., 'Updated DRC rules')",
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="rerun_requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who requested re-run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_precheck_reruns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="tool_versions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tool versions: {magic: '8.3.x', klayout: '0.28.x', pdk: 'gf180mcuD-v1.2.3'}",
            ),
        ),
    ]
