# Generated by Django 5.2.6 on 2025-11-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_project_submitted_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the access occurred"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("edit", "Edited"),
                            ("delete", "Deleted"),
                            ("submit", "Submitted"),
                            ("file_upload", "Uploaded File"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the admin user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string from the request"
                    ),
                ),
                (
                    "view_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the view that was accessed",
                        max_length=200,
                    ),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="Admin user who accessed the project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that was accessed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Access Log",
                "verbose_name_plural": "Project Access Logs",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["-accessed_at"], name="projects_pr_accesse_7225a3_idx"
                    ),
                    models.Index(
                        fields=["admin_user", "-accessed_at"],
                        name="projects_pr_admin_u_dade1b_idx",
                    ),
                    models.Index(
                        fields=["project", "-accessed_at"],
                        name="projects_pr_project_e4b13d_idx",
                    ),
                ],
            },
        ),
    ]
