# Generated by Django 5.2.6 on 2025-11-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_project_submitted_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="processed_filename",
            field=models.CharField(
                blank=True,
                help_text="Final filename after extraction/decompression pipeline",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="original_filename",
            field=models.CharField(
                help_text="Original filename when downloaded (immutable)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="FileProcessingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("download", "Download Error"),
                            ("extraction", "Extraction Error"),
                            ("validation", "Validation Error"),
                            ("pipeline", "Pipeline Error"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(help_text="User-friendly error message"),
                ),
                (
                    "error_detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical details: stack trace, context, etc. (superuser only)",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="projects.projectfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["project_file", "-occurred_at"],
                        name="projects_fi_project_29e518_idx",
                    ),
                    models.Index(
                        fields=["error_type", "-occurred_at"],
                        name="projects_fi_error_t_4ec9f5_idx",
                    ),
                ],
            },
        ),
    ]
