# Generated by Django 5.2.6 on 2025-11-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_downloadattempt_restructure"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="downloadattempt",
            new_name="projects_do_project_3295e4_idx",
            old_name="projects_do_project_1b0e8d_idx",
        ),
        migrations.RenameIndex(
            model_name="downloadattempt",
            new_name="projects_do_status_1c9c65_idx",
            old_name="projects_do_status_5f4c9a_idx",
        ),
        migrations.RenameIndex(
            model_name="downloadattempt",
            new_name="projects_do_last_ac_d4ed07_idx",
            old_name="projects_do_last_ac_8a3d2e_idx",
        ),
        migrations.RenameIndex(
            model_name="fileprocessingerror",
            new_name="projects_fi_downloa_8631d3_idx",
            old_name="projects_fi_downloa_7a6f2c_idx",
        ),
        migrations.RenameIndex(
            model_name="projectfilechunk",
            new_name="projects_pr_downloa_440be3_idx",
            old_name="projects_pr_downloa_4f8e3a_idx",
        ),
        migrations.RenameIndex(
            model_name="projectfilechunk",
            new_name="projects_pr_downloa_9092ee_idx",
            old_name="projects_pr_downloa_9c2d1b_idx",
        ),
    ]
