# Generated by Django 5.2.6 on 2025-11-21 04:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0015_rename_projects_do_project_1b0e8d_idx_projects_do_project_3295e4_idx_and_more",
        ),
    ]

    operations = [
        # Step 1: Add new fields to DownloadAttempt for worker tracking
        migrations.AddField(
            model_name="downloadattempt",
            name="worker_pid",
            field=models.IntegerField(blank=True, help_text="Process ID of worker executing this attempt", null=True),
        ),
        migrations.AddField(
            model_name="downloadattempt",
            name="worker_hostname",
            field=models.CharField(blank=True, help_text="Hostname of worker executing this attempt", max_length=255),
        ),
        migrations.AddField(
            model_name="downloadattempt",
            name="task_started_at",
            field=models.DateTimeField(blank=True, help_text="When Celery task started executing", null=True),
        ),
        # Step 2: Delete all existing DownloadAttempt records (clean break)
        # First delete records from tables that have FK to DownloadAttempt
        migrations.RunSQL(
            sql="DELETE FROM projects_projectfilechunk;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DELETE FROM projects_fileprocessingerror;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DELETE FROM projects_downloadattempt;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: Remove auto-retry fields from ProjectFile
        migrations.RemoveField(
            model_name="projectfile",
            name="auto_retry_enabled",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="retry_count",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="max_retries",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="next_retry_at",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="last_retry_at",
        ),
        # Step 4: Remove worker tracking fields from ProjectFile (moving to DownloadAttempt)
        migrations.RemoveField(
            model_name="projectfile",
            name="worker_pid",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="worker_hostname",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="task_started_at",
        ),
        # Step 5: Remove download_status field (will become @property)
        migrations.RemoveField(
            model_name="projectfile",
            name="download_status",
        ),
    ]
