# Generated by Django 5.2.6 on 2025-11-24 21:48

import django.core.validators
import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_refactor_download_retry_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=wafer_space.projects.models.project_file_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "gds",
                            "gdsii",
                            "gds2",
                            "oas",
                            "oasis",
                            "gz",
                            "zip",
                            "bz2",
                            "xz",
                        ]
                    )
                ],
            ),
        ),
    ]
