# Generated by Django 5.2.6 on 2025-11-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_increase_file_field_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="project_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturability_check",
                to="projects.projectfile",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturability_checks",
                to="projects.project",
            ),
        ),
    ]
