# Generated by Django 5.2.6 on 2025-11-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_populate_manufacturability_check_project_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="System error message if check failed to run (Docker, timeout, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="project_file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturability_check",
                to="projects.projectfile",
            ),
        ),
    ]
