# Generated by Django 5.2.6 on 2025-11-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_projectaccesslog_action"),
        ("projects", "0019_populate_manufacturability_check_project_file"),
    ]

    operations = []
