# Generated by Django 5.2.6 on 2025-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_add_manufacturability_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="top_cell",
            field=models.CharField(
                blank=True,
                help_text="Top-level cell name extracted from GDS/OASIS file",
                max_length=255,
            ),
        ),
    ]
