# Generated by Django 5.2.6 on 2025-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_projectaccesslog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectaccesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "Viewed"),
                    ("edit", "Edited"),
                    ("delete", "Deleted"),
                    ("access_denied", "Access Denied"),
                ],
                help_text="Type of action performed",
                max_length=20,
            ),
        ),
    ]
