# Generated by Django 5.2.6 on 2025-11-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_projectfile_top_cell"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturabilityCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this checkpoint was recorded"
                    ),
                ),
                (
                    "checkpoint_number",
                    models.IntegerField(
                        help_text="Sequential checkpoint number for ordering"
                    ),
                ),
                (
                    "elapsed_seconds",
                    models.FloatField(help_text="Seconds since check started"),
                ),
                (
                    "cpu_percent",
                    models.FloatField(
                        blank=True,
                        help_text="CPU usage percentage at this checkpoint",
                        null=True,
                    ),
                ),
                (
                    "cpu_total_usage",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total CPU usage in nanoseconds",
                        null=True,
                    ),
                ),
                (
                    "cpu_system_usage",
                    models.BigIntegerField(
                        blank=True,
                        help_text="System CPU usage in nanoseconds",
                        null=True,
                    ),
                ),
                (
                    "cpu_online_cpus",
                    models.IntegerField(
                        blank=True, help_text="Number of online CPUs", null=True
                    ),
                ),
                (
                    "memory_usage_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Memory usage in bytes", null=True
                    ),
                ),
                (
                    "memory_limit_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Memory limit in bytes", null=True
                    ),
                ),
                (
                    "memory_percent",
                    models.FloatField(
                        blank=True,
                        help_text="Memory usage as percentage of limit",
                        null=True,
                    ),
                ),
                (
                    "memory_cache_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Memory cache in bytes", null=True
                    ),
                ),
                (
                    "block_read_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Block device read bytes", null=True
                    ),
                ),
                (
                    "block_write_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Block device write bytes", null=True
                    ),
                ),
                (
                    "network_rx_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Network bytes received", null=True
                    ),
                ),
                (
                    "network_tx_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Network bytes transmitted", null=True
                    ),
                ),
                (
                    "container_state",
                    models.CharField(
                        blank=True,
                        help_text="Container state (running, exited, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturability_check",
                    models.ForeignKey(
                        help_text="The manufacturability check this checkpoint belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="projects.manufacturabilitycheck",
                    ),
                ),
            ],
            options={
                "ordering": ["checkpoint_number"],
                "indexes": [
                    models.Index(
                        fields=["manufacturability_check", "checkpoint_number"],
                        name="projects_ma_manufac_d6d031_idx",
                    ),
                    models.Index(
                        fields=["manufacturability_check", "timestamp"],
                        name="projects_ma_manufac_89cdbe_idx",
                    ),
                ],
            },
        ),
    ]
