# Generated by Django 5.2.6 on 2025-11-26 23:17

import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_manufacturabilitycheckpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="log_file",
            field=models.FileField(
                blank=True,
                help_text="Log file stored on filesystem (next to GDS file)",
                max_length=512,
                upload_to=wafer_space.projects.models.manufacturability_check_log_path,
            ),
        ),
    ]
