# Generated by Django 5.2.6 on 2025-11-16 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_manufacturabilitycheck_docker_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectComplianceCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_control_compliant",
                    models.BooleanField(
                        default=False,
                        help_text="User confirms compliance with EAR/ITAR export control regulations",
                    ),
                ),
                (
                    "end_use_statement",
                    models.TextField(
                        help_text="Description of intended end-use (commercial, research, educational, etc.)"
                    ),
                ),
                (
                    "not_restricted_entity",
                    models.BooleanField(
                        default=False,
                        help_text="User confirms they are not from a restricted country or sanctioned entity",
                    ),
                ),
                ("certified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which certification was submitted",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                ("admin_reviewed", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "admin_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_certification",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Certification",
                "verbose_name_plural": "Compliance Certifications",
                "indexes": [
                    models.Index(
                        fields=["certified_at"], name="projects_pr_certifi_94cc79_idx"
                    ),
                    models.Index(
                        fields=["admin_reviewed"], name="projects_pr_admin_r_246f71_idx"
                    ),
                ],
            },
        ),
    ]
