# Generated by Django 5.2.6 on 2025-11-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_projectcompliancecertification"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="expected_hash_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash provided by user for verification",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="hash_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
