# Generated by Django 5.2.6 on 2025-11-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_add_sha256_hash_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_command",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full docker run command for reproducibility",
            ),
        ),
    ]
