# Generated by Django 5.2.6 on 2025-11-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_manufacturabilitycheck_docker_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When check entered/re-entered the QUEUED state",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("starting", "Starting"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
