# Generated by Django 5.2.6 on 2025-11-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_manufacturabilitycheck_queued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="worker_hostname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hostname of worker executing this check",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="worker_pid",
            field=models.IntegerField(
                blank=True,
                help_text="Process ID of worker executing this check",
                null=True,
            ),
        ),
    ]
