# Generated by Django 5.2.6 on 2025-11-28 23:55

import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_manufacturabilitycheck_worker_hostname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="runs_archive",
            field=models.FileField(
                blank=True,
                help_text="Tar archive of detailed step logs from precheck runs/ directory",
                max_length=512,
                upload_to=wafer_space.projects.models.manufacturability_check_runs_path,
            ),
        ),
    ]
