# Generated by Django 5.2.6 on 2025-11-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_alter_projectaccesslog_action"),
        ("projects", "0030_manufacturabilitycheck_runs_archive"),
    ]

    operations = []
