# Generated by Django 5.2.6 on 2025-11-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_merge_20251129_0451"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slot_size",
            field=models.CharField(
                choices=[
                    ("1x1", "1×1 (Full Slot)"),
                    ("0p5x1", "0.5×1 (Half Width)"),
                    ("1x0p5", "1×0.5 (Half Height)"),
                    ("0p5x0p5", "0.5×0.5 (Quarter Slot)"),
                ],
                default="1x1",
                help_text="Die slot size for manufacturing",
                max_length=10,
            ),
        ),
    ]
