# Generated by Django 5.2.6 on 2025-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_project_slot_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slot_size",
            field=models.CharField(
                choices=[
                    ("1x1", "1x1 - Full Slot (3.88mm x 5.07mm)"),
                    ("0p5x1", "0.5x1 - Half Width (1.94mm x 5.07mm)"),
                    ("1x0p5", "1x0.5 - Half Height (3.88mm x 2.535mm)"),
                    ("0p5x0p5", "0.5x0.5 - Quarter Slot (1.94mm x 2.535mm)"),
                ],
                default="1x1",
                help_text="Die slot size for manufacturing",
                max_length=10,
            ),
        ),
    ]
