# Generated by Django 5.2.6 on 2025-11-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_alter_project_slot_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturabilitycheck",
            options={
                "ordering": ["-celery_job_started_at"],
                "verbose_name": "Manufacturability Check",
                "verbose_name_plural": "Manufacturability Checks",
            },
        ),
        migrations.RenameField(
            model_name="manufacturabilitycheck",
            old_name="completed_at",
            new_name="celery_job_finished_at",
        ),
        migrations.RenameField(
            model_name="manufacturabilitycheck",
            old_name="started_at",
            new_name="celery_job_started_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="queued_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="task_id",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="worker_hostname",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="worker_pid",
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="celery_job_dispatched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When job was dispatched to Celery queue",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="celery_job_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the Celery job processing this check",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="celery_worker_hostname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hostname of Celery worker executing this check",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="celery_worker_pid",
            field=models.IntegerField(
                blank=True,
                help_text="Process ID of Celery worker executing this check",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_container_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of Docker container running the analysis",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_container_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When Docker container started", null=True
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched", "Dispatched"),
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
