# Generated by Django 5.2.6 on 2025-11-30 04:23

from django.db import migrations


def migrate_status_forward(apps, schema_editor):
    """Migrate old status values to new status values."""
    ManufacturabilityCheck = apps.get_model("projects", "ManufacturabilityCheck")

    # Map old status values to new values
    status_mapping = {
        "queued": "pending",
        "starting": "dispatched",
        "processing": "running",
        "completed": "finished",
        "failed": "error",
        # "cancelled" stays the same
    }

    for old_status, new_status in status_mapping.items():
        ManufacturabilityCheck.objects.filter(status=old_status).update(
            status=new_status
        )


def migrate_status_backward(apps, schema_editor):
    """Reverse migration: new status values back to old values."""
    ManufacturabilityCheck = apps.get_model("projects", "ManufacturabilityCheck")

    # Map new status values back to old values
    status_mapping = {
        "pending": "queued",
        "dispatched": "starting",
        "running": "processing",
        "finished": "completed",
        "error": "failed",
        # "cancelled" stays the same
    }

    for new_status, old_status in status_mapping.items():
        ManufacturabilityCheck.objects.filter(status=new_status).update(
            status=old_status
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_rename_manufacturability_check_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
    ]
