# Generated by Django 5.2.6 on 2025-11-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_manufacturabilitycheck_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched", "Dispatched"),
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("error", "Error"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
