# Generated by Django 5.2.6 on 2025-12-02 10:37

import django.db.models.deletion
import wafer_space.projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_add_cancelling_status"),
        ("shuttles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="4-character alphanumeric project identifier (A-Z, 0-9)",
                max_length=4,
                null=True,
                validators=[wafer_space.projects.models.validate_project_id],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="shuttle",
            field=models.ForeignKey(
                blank=True,
                help_text="Shuttle run this project is assigned to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="shuttles.shuttle",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["shuttle", "project_id"], name="projects_pr_shuttle_1714db_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("shuttle", "project_id"), name="unique_project_id_per_shuttle"
            ),
        ),
    ]
