# Generated by Django 5.2.6 on 2025-12-02 10:46

import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_project_project_id_project_shuttle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="4-character alphanumeric project identifier (A-Z, 0-9)",
                max_length=4,
                validators=[wafer_space.projects.models.validate_project_id],
            ),
        ),
    ]
