# Generated by Django 5.2.6 on 2025-12-02 12:39

import logging
from typing import ClassVar

from django.db import migrations

logger = logging.getLogger(__name__)


def populate_shuttle_and_project_ids(apps, _schema_editor):
    """Populate shuttle and project_id fields for existing projects.

    Assigns all projects without a shuttle to the G801 shuttle and generates
    unique 4-character project IDs for projects that don't have one.
    """
    Project = apps.get_model("projects", "Project")
    Shuttle = apps.get_model("shuttles", "Shuttle")

    # Get or create G801 shuttle
    g801, created = Shuttle.objects.get_or_create(
        name="G801",
        defaults={
            "description": "Initial shuttle run for wafer.space",
            "status": "open",
            "max_slots": 100,
            "available_slots": 100,
        },
    )

    if created:
        logger.info("Created G801 shuttle: %s", g801.id)
    else:
        logger.info("Using existing G801 shuttle: %s", g801.id)

    # Get projects without a shuttle
    projects_to_migrate = Project.objects.filter(shuttle__isnull=True)
    count = projects_to_migrate.count()

    if count == 0:
        logger.info("No projects to migrate")
        return

    logger.info("Found %d projects to migrate to G801", count)

    # Generate sequential project IDs starting from P001
    # Format: P001, P002, P003, etc.
    next_id = 1
    for project in projects_to_migrate:
        project_id = f"P{next_id:03d}"  # P001, P002, P003...

        # Ensure uniqueness within the shuttle
        while Project.objects.filter(shuttle=g801, project_id=project_id).exists():
            next_id += 1
            project_id = f"P{next_id:03d}"

        project.shuttle = g801
        project.project_id = project_id
        project.save(update_fields=["shuttle", "project_id"])

        logger.info("  Migrated: %s -> G801:%s", project.name, project_id)
        next_id += 1

    logger.info("Successfully migrated %d projects to G801", count)


def reverse_migration(apps, _schema_editor):
    """Reverse the data migration by clearing shuttle and project_id."""
    Project = apps.get_model("projects", "Project")

    # Clear shuttle and project_id for all projects
    projects = Project.objects.filter(shuttle__isnull=False)
    count = projects.count()

    projects.update(shuttle=None, project_id="")

    logger.info("Cleared shuttle and project_id for %d projects", count)


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("projects", "0040_alter_project_project_id"),
        ("shuttles", "0002_alter_shuttle_name"),
    ]

    operations: ClassVar[list[migrations.RunPython]] = [
        migrations.RunPython(populate_shuttle_and_project_ids, reverse_migration),
    ]
