# Generated by Django 5.2.6 on 2025-12-02 12:39

from django.db import migrations


def populate_shuttle_and_project_ids(apps, schema_editor):
    """Populate shuttle and project_id fields for existing projects.

    Assigns all projects without a shuttle to the G801 shuttle and generates
    unique 4-character project IDs for projects that don't have one.
    """
    Project = apps.get_model("projects", "Project")
    Shuttle = apps.get_model("shuttles", "Shuttle")

    # Get or create G801 shuttle
    g801, created = Shuttle.objects.get_or_create(
        name="G801",
        defaults={
            "description": "Initial shuttle run for wafer.space",
            "status": "open",
            "max_slots": 100,
            "available_slots": 100,
        },
    )

    if created:
        print(f"Created G801 shuttle: {g801.id}")
    else:
        print(f"Using existing G801 shuttle: {g801.id}")

    # Get projects without a shuttle
    projects_to_migrate = Project.objects.filter(shuttle__isnull=True)
    count = projects_to_migrate.count()

    if count == 0:
        print("No projects to migrate")
        return

    print(f"Found {count} projects to migrate to G801")

    # Generate sequential project IDs starting from P001
    # Format: P001, P002, P003, etc.
    for index, project in enumerate(projects_to_migrate, start=1):
        project_id = f"P{index:03d}"  # P001, P002, P003...

        # Ensure uniqueness within the shuttle
        while Project.objects.filter(shuttle=g801, project_id=project_id).exists():
            index += 1
            project_id = f"P{index:03d}"

        project.shuttle = g801
        project.project_id = project_id
        project.save(update_fields=["shuttle", "project_id"])

        print(f"  Migrated: {project.name} -> G801:{project_id}")

    print(f"Successfully migrated {count} projects to G801")


def reverse_migration(apps, schema_editor):
    """Reverse the data migration by clearing shuttle and project_id."""
    Project = apps.get_model("projects", "Project")

    # Clear shuttle and project_id for all projects
    projects = Project.objects.filter(shuttle__isnull=False)
    count = projects.count()

    projects.update(shuttle=None, project_id="")

    print(f"Cleared shuttle and project_id for {count} projects")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_alter_project_project_id"),
        ("shuttles", "0002_alter_shuttle_name"),
    ]

    operations = [
        migrations.RunPython(populate_shuttle_and_project_ids, reverse_migration),
    ]
