# Generated by Django 5.2.6 on 2025-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0041_populate_shuttle_and_project_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slot_size",
            field=models.CharField(
                choices=[
                    ("1x1", "1×1"),
                    ("0p5x1", "0.5×1"),
                    ("1x0p5", "1×0.5"),
                    ("0p5x0p5", "0.5×0.5"),
                ],
                default="1x1",
                help_text="Die slot size for manufacturing",
                max_length=20,
            ),
        ),
    ]
