# Generated by Django 5.2.6 on 2025-12-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0042_alter_project_slot_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_server_id",
            field=models.CharField(
                blank=True,
                help_text="ID of Docker server running this check (from DOCKER_SERVERS setting)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched", "Dispatched"),
                    ("dispatching", "Dispatching"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("analyzing", "Analyzing"),
                    ("finished", "Finished"),
                    ("error", "Error"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
