# Generated by Django 5.2.6 on 2025-12-04 10:00

from typing import ClassVar

import django.core.validators
import wafer_space.projects.models
import wafer_space.projects.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("projects", "0042_alter_project_slot_size"),
    ]

    operations: ClassVar[list[migrations.AlterField]] = [
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="log_file",
            field=models.FileField(
                blank=True,
                help_text="Log file stored on filesystem (next to GDS file)",
                max_length=512,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.manufacturability_check_log_path,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="runs_archive",
            field=models.FileField(
                blank=True,
                help_text="Tar archive of detailed step logs from precheck runs/ directory",
                max_length=512,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.manufacturability_check_runs_path,
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.project_file_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "gds",
                            "gdsii",
                            "gds2",
                            "oas",
                            "oasis",
                            "gz",
                            "zip",
                            "bz2",
                            "xz",
                        ]
                    )
                ],
            ),
        ),
    ]
