# Generated by Claude Code on 2025-12-04 21:00

import logging
import os
from pathlib import Path
from typing import ClassVar

from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)


def fix_project_directory_permissions(apps, _schema_editor):
    """Fix permissions on existing project directories to 775 (group write).

    Changes all project directories under media/projects/ to 775 (rwxrwxr-x)
    to enable group write access. This allows Docker containers running as
    www-data to write to these directories.

    Idempotent: Safe to run multiple times.
    """
    Project = apps.get_model("projects", "Project")

    # Get media root from settings
    media_root = Path(settings.MEDIA_ROOT)
    projects_dir = media_root / "projects"

    # Check if projects directory exists
    if not projects_dir.exists():
        logger.info("Projects directory does not exist yet: %s", projects_dir)
        return

    # Get all project UUIDs from database
    project_ids = Project.objects.values_list("id", flat=True)
    count = project_ids.count()

    if count == 0:
        logger.info("No projects found in database")
        return

    logger.info("Checking permissions for %d project directories", count)

    fixed_count = 0
    already_correct_count = 0
    missing_count = 0
    error_count = 0

    for project_id in project_ids:
        project_path = projects_dir / str(project_id)

        # Skip if directory doesn't exist
        if not project_path.exists():
            missing_count += 1
            continue

        # Skip if not a directory
        if not project_path.is_dir():
            logger.warning("Path exists but is not a directory: %s", project_path)
            error_count += 1
            continue

        try:
            # Get current permissions
            current_mode = project_path.stat().st_mode
            current_perms = current_mode & 0o777

            # Target permissions: 775 (rwxrwxr-x)
            target_perms = 0o775

            if current_perms != target_perms:
                # Change permissions to 775
                os.chmod(project_path, target_perms)
                logger.info(
                    "Fixed permissions for %s: %03o -> %03o",
                    project_path,
                    current_perms,
                    target_perms,
                )
                fixed_count += 1
            else:
                # Already correct
                already_correct_count += 1

        except OSError:
            logger.exception(
                "Failed to chmod %s",
                project_path,
            )
            error_count += 1

    logger.info(
        "Permission fix complete: %d fixed, %d already correct, %d missing, %d errors",
        fixed_count,
        already_correct_count,
        missing_count,
        error_count,
    )


def reverse_migration(_apps, _schema_editor):
    """Reverse migration (no-op with warning).

    We don't reverse permission changes as it could break existing functionality.
    """
    logger.warning(
        "Reverse migration for directory permissions is a no-op. "
        "Permission changes are not reversed as it could break functionality."
    )


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("projects", "0043_alter_manufacturabilitycheck_log_file_and_more"),
    ]

    operations: ClassVar[list[migrations.RunPython]] = [
        migrations.RunPython(fix_project_directory_permissions, reverse_migration),
    ]
