# Generated by Django 5.2.6 on 2025-12-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0043_add_docker_server_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="docker_server_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of Docker server running this check (from DOCKER_SERVERS setting)",
                max_length=64,
            ),
        ),
    ]
