# Generated by Django 5.2.6 on 2025-12-09 06:46

import django.db.models.deletion
import simple_history.models
import uuid
import wafer_space.projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0044_fix_project_directory_permissions"),
        ("shuttles", "0007_alter_shuttleslot_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "slot_size",
                    models.CharField(
                        choices=[
                            ("1x1", "1×1"),
                            ("0p5x1", "0.5×1"),
                            ("1x0p5", "1×0.5"),
                            ("0p5x0p5", "0.5×0.5"),
                        ],
                        default="1x1",
                        help_text="Die slot size for manufacturing",
                        max_length=20,
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="4-character alphanumeric project identifier (A-Z, 0-9)",
                        max_length=4,
                        validators=[wafer_space.projects.models.validate_project_id],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("checking", "Checking Manufacturability"),
                            ("manufacturable", "Manufacturable"),
                            ("not_manufacturable", "Not Manufacturable"),
                            ("assigned", "Assigned to Shuttle"),
                            ("production", "In Production"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_manufacturable", models.BooleanField(blank=True, null=True)),
                (
                    "manufacturability_errors",
                    models.JSONField(blank=True, default=list),
                ),
                ("check_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shuttle",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Shuttle run this project is assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="shuttles.shuttle",
                    ),
                ),
                (
                    "submitted_file",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The file that was submitted for manufacturing",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.projectfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Project",
                "verbose_name_plural": "historical Projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
