# Generated by Django 5.2.6 on 2025-12-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0044_fix_docker_server_id_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="analysis_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When log analysis completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="container_finished_at",
            field=models.DateTimeField(
                blank=True, help_text="When container exited", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="container_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When container was confirmed running", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="dispatching_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When check entered DISPATCHING (image pull started)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="starting_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When check entered STARTING (container creation started)",
                null=True,
            ),
        ),
    ]
