# Generated by Django 5.2.6 on 2025-12-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0045_historicalproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether this design should be publicly visible on the platform",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether this design should be publicly visible on the platform",
            ),
        ),
    ]
