# Generated by Django 5.2.6 on 2025-12-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0045_add_granular_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_exit_code",
            field=models.IntegerField(
                blank=True, help_text="Exit code from Docker container", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="logs_downloaded_until",
            field=models.FloatField(
                blank=True,
                help_text="Unix timestamp (with nanoseconds) for incremental log fetch",
                null=True,
            ),
        ),
    ]
