# Generated by Django 5.2.6 on 2025-12-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0046_add_docker_exit_code_and_logs_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturabilityCheckTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(help_text="Celery task ID", max_length=255),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the Celery task (e.g., do_running)",
                        max_length=255,
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was queued"
                    ),
                ),
                (
                    "manufacturability_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_task",
                        to="projects.manufacturabilitycheck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturability Check Task",
                "verbose_name_plural": "Manufacturability Check Tasks",
            },
        ),
    ]
