# Generated by Django 5.2.6 on 2025-12-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0046_add_is_public_to_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("proprietary", "Proprietary (All Rights Reserved)"),
                    ("Apache-2.0", "Apache License 2.0"),
                    ("MIT", "MIT License"),
                    ("BSD-3-Clause", "BSD 3-Clause License"),
                    ("ISC", "ISC License"),
                    ("CERN-OHL-P-2.0", "CERN Open Hardware License (Permissive)"),
                    ("SHL-2.0", "Solderpad Hardware License 2.0"),
                    ("SHL-2.1", "Solderpad Hardware License 2.1"),
                    ("CC0-1.0", "CC0 1.0 (Public Domain)"),
                    ("CC-BY-4.0", "Creative Commons Attribution 4.0"),
                    ("other", "Other Open Source License"),
                ],
                default="proprietary",
                help_text="License under which this project is released",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="other_license_spdx_id",
            field=models.CharField(
                blank=True,
                help_text="SPDX identifier when license_type is 'Other'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="proprietary_terms_cached",
            field=models.TextField(
                blank=True, help_text="Cached content from proprietary_terms_url"
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="proprietary_terms_cached_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When proprietary terms were last cached",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="proprietary_terms_url",
            field=models.URLField(
                blank=True, help_text="URL to proprietary license terms", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="repository_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the project's source repository",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("proprietary", "Proprietary (All Rights Reserved)"),
                    ("Apache-2.0", "Apache License 2.0"),
                    ("MIT", "MIT License"),
                    ("BSD-3-Clause", "BSD 3-Clause License"),
                    ("ISC", "ISC License"),
                    ("CERN-OHL-P-2.0", "CERN Open Hardware License (Permissive)"),
                    ("SHL-2.0", "Solderpad Hardware License 2.0"),
                    ("SHL-2.1", "Solderpad Hardware License 2.1"),
                    ("CC0-1.0", "CC0 1.0 (Public Domain)"),
                    ("CC-BY-4.0", "Creative Commons Attribution 4.0"),
                    ("other", "Other Open Source License"),
                ],
                default="proprietary",
                help_text="License under which this project is released",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="other_license_spdx_id",
            field=models.CharField(
                blank=True,
                help_text="SPDX identifier when license_type is 'Other'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proprietary_terms_cached",
            field=models.TextField(
                blank=True, help_text="Cached content from proprietary_terms_url"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proprietary_terms_cached_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When proprietary terms were last cached",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proprietary_terms_url",
            field=models.URLField(
                blank=True, help_text="URL to proprietary license terms", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="repository_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the project's source repository",
                max_length=500,
            ),
        ),
    ]
