# Generated by Django 5.2.6 on 2025-12-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0045_alter_project_id_alter_project_project_id"),
        ("projects", "0046_add_is_public_to_project"),
    ]

    operations = []
