# Generated by Django 5.2.6 on 2025-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_add_manufacturability_check_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturabilitycheck",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Manufacturability Check",
                "verbose_name_plural": "Manufacturability Checks",
            },
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_dispatched_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_finished_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_id",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_started_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_worker_hostname",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_worker_pid",
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("analyzing", "Analyzing"),
                    ("finished", "Finished"),
                    ("error", "Error"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
