# Generated by Django 5.2.6 on 2025-12-10 11:09

import uuid
import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_add_project_metadata_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Internal UUID primary key. Use for DB queries and API requests.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="project_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="User-chosen 4-character code (A-Z, 0-9). Unique per shuttle, not globally. See class docstring.",
                max_length=4,
                validators=[wafer_space.projects.models.validate_project_id],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Internal UUID primary key. Use for DB queries and API requests.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="User-chosen 4-character code (A-Z, 0-9). Unique per shuttle, not globally. See class docstring.",
                max_length=4,
                validators=[wafer_space.projects.models.validate_project_id],
            ),
        ),
    ]
