# Generated by Django 5.2.6 on 2025-12-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0044_fix_project_directory_permissions"),
        ("projects", "0048_remove_deprecated_celery_fields"),
    ]

    operations = []
