# Generated by Django 5.2.6 on 2025-12-10 12:11

import django.db.models.deletion
import wafer_space.projects.models
import wafer_space.projects.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0048_alter_historicalproject_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturabilitycheck",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Manufacturability Check",
                "verbose_name_plural": "Manufacturability Checks",
            },
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_dispatched_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_finished_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_id",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_job_started_at",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_worker_hostname",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="celery_worker_pid",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="docker_container_started_at",
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="analysis_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When log analysis completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="container_finished_at",
            field=models.DateTimeField(
                blank=True, help_text="When container exited", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="container_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When container was confirmed running", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="dispatching_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When check entered DISPATCHING (image pull started)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_exit_code",
            field=models.IntegerField(
                blank=True, help_text="Exit code from Docker container", null=True
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_layer_export",
            field=models.FileField(
                blank=True,
                help_text="Compressed tarball of container filesystem changes for debugging",
                max_length=512,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.manufacturability_check_docker_layer_path,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_layer_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of docker layer export",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_server_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of Docker server running this check (from DOCKER_SERVERS setting)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="log_file_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of log file",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="logs_downloaded_until",
            field=models.FloatField(
                blank=True,
                help_text="Unix timestamp (with nanoseconds) for incremental log fetch",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="output_gds",
            field=models.FileField(
                blank=True,
                help_text="Output GDS file from precheck (modified design with QR code, etc.)",
                max_length=512,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.manufacturability_check_output_gds_path,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="output_gds_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of output GDS file",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="runs_archive_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of runs archive",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="starting_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When check entered STARTING (container creation started)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheckpoint",
            name="raw_stats_json",
            field=models.JSONField(
                blank=True,
                help_text="Raw Docker stats API response for debugging",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("analyzing", "Analyzing"),
                    ("finished", "Finished"),
                    ("error", "Error"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ManufacturabilityCheckTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(help_text="Celery task ID", max_length=255),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the Celery task (e.g., do_running)",
                        max_length=255,
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the task was queued"
                    ),
                ),
                (
                    "manufacturability_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_task",
                        to="projects.manufacturabilitycheck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturability Check Task",
                "verbose_name_plural": "Manufacturability Check Tasks",
            },
        ),
    ]
