# Generated by Django 5.2.6 on 2025-12-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0049_merge_20251205_0621"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="docker_container_started_at",
        ),
    ]
