# Generated by Django 5.2.6 on 2025-12-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0049_docker_polling_architecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="max_retries",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="retry_count",
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="parent_check",
            field=models.ForeignKey(
                blank=True,
                help_text="Original check this is a retry of (null if not a retry)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retry_checks",
                to="projects.manufacturabilitycheck",
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="trigger_reason",
            field=models.CharField(
                choices=[
                    ("initial", "Initial Check"),
                    ("drc_update", "DRC Rules Updated"),
                    ("admin_rerun", "Admin Requested Re-run"),
                    ("retry", "Retry After Error"),
                ],
                default="initial",
                help_text="Why this check was triggered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="project_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturability_checks",
                to="projects.projectfile",
            ),
        ),
    ]
