# Generated by Django 5.2.6 on 2025-12-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_multi_check_refactor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="check_completed_at",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="is_manufacturable",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="manufacturability_errors",
        ),
        migrations.RemoveField(
            model_name="project",
            name="check_completed_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_manufacturable",
        ),
        migrations.RemoveField(
            model_name="project",
            name="manufacturability_errors",
        ),
    ]
