# Generated by Django 5.2.6 on 2025-12-06 05:00

import wafer_space.projects.models
import wafer_space.projects.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_remove_docker_container_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_layer_export",
            field=models.FileField(
                blank=True,
                help_text="Compressed tarball of container filesystem changes for debugging",
                max_length=512,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.manufacturability_check_docker_layer_path,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="docker_layer_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of docker layer export",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="log_file_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of log file",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="output_gds",
            field=models.FileField(
                blank=True,
                help_text="Output GDS file from precheck (modified design with QR code, etc.)",
                max_length=512,
                storage=wafer_space.projects.storage.ProjectFileStorage(),
                upload_to=wafer_space.projects.models.manufacturability_check_output_gds_path,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="output_gds_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of output GDS file",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="runs_archive_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 checksum of runs archive",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="manufacturabilitycheckpoint",
            name="raw_stats_json",
            field=models.JSONField(
                blank=True,
                help_text="Raw Docker stats API response for debugging",
                null=True,
            ),
        ),
    ]
