# Generated by Django 5.2.6 on 2025-12-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_merge_20251210_0500"),
        ("projects", "0048_alter_historicalproject_id_and_more"),
        ("projects", "0051_add_output_fields_and_raw_stats"),
    ]

    operations = []
