# Generated by Django 5.2.6 on 2025-12-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_remove_project_manufacturability_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="estimated_cost",
        ),
        migrations.RemoveField(
            model_name="project",
            name="estimated_cost",
        ),
    ]
