# Generated by Django 5.2.6 on 2025-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_add_output_fields_and_raw_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="trigger_reason",
            field=models.CharField(
                choices=[
                    ("initial", "Initial Check"),
                    ("drc_update", "DRC Rules Updated"),
                    ("admin_rerun", "Admin Requested Re-run"),
                    ("retry", "Retry After Error"),
                ],
                default="initial",
                help_text="Why this check was triggered",
                max_length=20,
            ),
        ),
    ]
