# Generated by Django 5.2.6 on 2025-12-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_remove_unused_estimated_cost_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatching", "Dispatching"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("analyzing", "Analyzing"),
                    ("cancelling", "Cancelling"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
