# Generated by Django 5.2.6 on 2025-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_remove_unused_estimated_cost_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecheckImageRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        help_text="SHA256 digest (e.g., sha256:abc123...)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the image was pushed to GHCR",
                        null=True,
                    ),
                ),
                (
                    "git_commit_sha",
                    models.CharField(
                        blank=True,
                        help_text="Git commit from image labels",
                        max_length=40,
                    ),
                ),
                (
                    "precheck_version",
                    models.CharField(
                        blank=True,
                        help_text="Precheck tool version (e.g., 1.5.2)",
                        max_length=50,
                    ),
                ),
                (
                    "pdk_version",
                    models.CharField(
                        blank=True,
                        help_text="PDK version (if available)",
                        max_length=50,
                    ),
                ),
                (
                    "tool_versions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tool versions dict (e.g., {magic: '8.3.x', klayout: '0.28.x'})",
                    ),
                ),
                (
                    "metadata_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When GHCR metadata was last fetched",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["digest"], name="projects_pr_digest_42b6c9_idx"
                    ),
                    models.Index(
                        fields=["-first_seen_at"], name="projects_pr_first_s_2bbfc8_idx"
                    ),
                ],
            },
        ),
    ]
