# Generated by Django 5.2.6 on 2025-12-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_add_trigger_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturabilitycheck",
            name="parent_check",
            field=models.ForeignKey(
                blank=True,
                help_text="Original check this is a retry of (null if not a retry)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retry_checks",
                to="projects.manufacturabilitycheck",
            ),
        ),
    ]
