# Generated by Django 5.2.6 on 2025-12-09 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_add_parent_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturabilitycheck",
            name="project_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturability_checks",
                to="projects.projectfile",
            ),
        ),
    ]
