# Generated by Django 5.2.6 on 2025-12-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_add_precheck_image_revision"),
        ("projects", "0053_alter_manufacturabilitycheck_status_choices"),
    ]

    operations = []
