# Generated by Django 5.2.6 on 2025-12-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_convert_project_file_to_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="check_completed_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_manufacturable",
        ),
        migrations.RemoveField(
            model_name="project",
            name="manufacturability_errors",
        ),
    ]
