# Generated by Django 5.2.6 on 2025-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_merge_20251214_0350"),
    ]

    operations = [
        migrations.AddField(
            model_name="precheckimagerevision",
            name="commit_date",
            field=models.DateTimeField(
                blank=True, help_text="When the git commit was made", null=True
            ),
        ),
        migrations.AddField(
            model_name="precheckimagerevision",
            name="commit_message",
            field=models.CharField(
                blank=True, help_text="First line of git commit message", max_length=255
            ),
        ),
    ]
