# Generated by Django 5.2.6 on 2026-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_add_commit_info_to_precheck_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='chip_on_board',
            field=models.BooleanField(default=False, help_text='Run extra Chip-on-Board (CoB) compatibility checks during the manufacturability precheck.', verbose_name='Request Chip-on-Board (CoB) packaging'),
        ),
        migrations.AddField(
            model_name='project',
            name='chip_on_board',
            field=models.BooleanField(default=False, help_text='Run extra Chip-on-Board (CoB) compatibility checks during the manufacturability precheck.', verbose_name='Request Chip-on-Board (CoB) packaging'),
        ),
    ]
