# Generated by Django 5.2.6 on 2025-12-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_remove_project_manufacturability_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="max_retries",
        ),
        migrations.RemoveField(
            model_name="manufacturabilitycheck",
            name="retry_count",
        ),
    ]
