# Generated by Django 5.2.6 on 2026-06-09 03:32

import wafer_space.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_alter_manufacturabilitycheck_trigger_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='crowd_supply_order_id',
            field=models.CharField(blank=True, default='', help_text='Crowd Supply order number, e.g. 327373 (optional).', max_length=20, validators=[wafer_space.projects.models.validate_crowd_supply_order_id]),
        ),
        migrations.AddField(
            model_name='project',
            name='crowd_supply_order_id',
            field=models.CharField(blank=True, default='', help_text='Crowd Supply order number, e.g. 327373 (optional).', max_length=20, validators=[wafer_space.projects.models.validate_crowd_supply_order_id]),
        ),
    ]
