# Generated by Django 5.2.6 on 2026-07-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_historicalproject_crowd_supply_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precheckimagerevision',
            name='metadata_fetch_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of metadata fetch attempts (requeue stops at cap)'),
        ),
        migrations.AddField(
            model_name='precheckimagerevision',
            name='metadata_fetch_last_error',
            field=models.CharField(blank=True, help_text='Error from the most recent failed metadata fetch', max_length=255),
        ),
    ]
