# Generated by Django 5.2.6 on 2026-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_precheckimagerevision_metadata_fetch_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturabilitycheck',
            name='trigger_reason',
            field=models.CharField(choices=[('initial', 'Initial Check'), ('drc_update', 'DRC Rules Updated'), ('admin_rerun', 'Admin Requested Re-run'), ('retry', 'Retry After Error'), ('cob_change', 'Chip-on-Board Option Changed'), ('duplicated', 'Project Duplicated')], default='initial', help_text='Why this check was triggered', max_length=20),
        ),
    ]
