# Generated by Django 5.2.6 on 2025-09-23 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('open', 'Open for Submissions'), ('full', 'Full'), ('locked', 'Locked'), ('production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('max_slots', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('reserved_slots', models.PositiveIntegerField(default=0)),
                ('available_slots', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_deadline', models.DateTimeField(blank=True, help_text='Deadline for project submissions', null=True)),
                ('production_start_date', models.DateTimeField(blank=True, help_text='Expected production start date', null=True)),
                ('estimated_completion_date', models.DateTimeField(blank=True, help_text='Estimated completion date', null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, help_text='Actual completion date', null=True)),
                ('technology_node', models.CharField(blank=True, help_text='Manufacturing technology node (e.g., 180nm, 65nm)', max_length=50)),
                ('foundry', models.CharField(blank=True, help_text='Manufacturing foundry', max_length=100)),
                ('wafer_size', models.CharField(blank=True, help_text='Wafer size (e.g., 8 inch, 12 inch)', max_length=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_per_slot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Shuttle',
                'verbose_name_plural': 'Shuttles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'submission_deadline'], name='shuttles_sh_status_9539ce_idx'), models.Index(fields=['status', 'created_at'], name='shuttles_sh_status_2d8e85_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShuttleManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_data', models.JSONField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shuttle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='shuttles.shuttle')),
            ],
            options={
                'verbose_name': 'Shuttle Manifest',
                'verbose_name_plural': 'Shuttle Manifests',
                'ordering': ['-generated_at'],
                'unique_together': {('shuttle', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ShuttleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuttle_slots', to='projects.project')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slots', to=settings.AUTH_USER_MODEL)),
                ('shuttle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shuttles.shuttle')),
            ],
            options={
                'verbose_name': 'Shuttle Slot',
                'verbose_name_plural': 'Shuttle Slots',
                'ordering': ['shuttle', 'slot_number'],
                'indexes': [models.Index(fields=['shuttle', 'status'], name='shuttles_sh_shuttle_58af80_idx'), models.Index(fields=['project', 'status'], name='shuttles_sh_project_6c955a_idx')],
                'unique_together': {('shuttle', 'slot_number')},
            },
        ),
    ]
