# Generated by Django 5.2.6 on 2025-12-02 10:51

import wafer_space.shuttles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttle",
            name="name",
            field=models.CharField(
                help_text="Shuttle ID (format: G8XX where XX are two digits, e.g., G801)",
                max_length=4,
                unique=True,
                validators=[wafer_space.shuttles.models.validate_shuttle_id],
            ),
        ),
    ]
