# Generated by Django 5.2.6 on 2025-12-02 14:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0041_populate_shuttle_and_project_ids"),
        ("shuttles", "0002_alter_shuttle_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, remove old unique constraint that references slot_number
        migrations.AlterUniqueTogether(
            name="shuttleslot",
            unique_together=set(),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name="shuttleslot",
            name="shuttles_sh_project_6c955a_idx",
        ),
        # Add new fields
        migrations.AddField(
            model_name="shuttle",
            name="grid_config_file",
            field=models.CharField(
                blank=True,
                help_text="Path to YAML grid configuration (e.g., shuttles/G801-layout.yaml)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="shuttleslot",
            name="column",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Grid column index (0-based)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="shuttleslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="shuttleslot",
            name="row",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Grid row index (0-based)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="shuttleslot",
            name="slot_size",
            field=models.CharField(
                choices=[
                    ("1x1", "1×1 - Full Slot (3.88mm × 5.07mm = 19.67mm²)"),
                    ("0p5x1", "0.5×1 - Half Width (1.94mm × 5.07mm = 9.84mm²)"),
                    ("1x0p5", "1×0.5 - Half Height (3.88mm × 2.535mm = 9.84mm²)"),
                    ("0p5x0p5", "0.5×0.5 - Quarter Slot (1.94mm × 2.535mm = 4.92mm²)"),
                ],
                default="1x1",
                help_text="Physical size of this grid cell",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shuttleslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="shuttleslot",
            name="height",
        ),
        migrations.RemoveField(
            model_name="shuttleslot",
            name="position_x",
        ),
        migrations.RemoveField(
            model_name="shuttleslot",
            name="position_y",
        ),
        migrations.RemoveField(
            model_name="shuttleslot",
            name="slot_number",
        ),
        migrations.RemoveField(
            model_name="shuttleslot",
            name="width",
        ),
        # Now set new ordering and constraints
        migrations.AlterModelOptions(
            name="shuttleslot",
            options={
                "ordering": ["shuttle", "row", "column"],
                "verbose_name": "Shuttle Slot",
                "verbose_name_plural": "Shuttle Slots",
            },
        ),
        migrations.AlterUniqueTogether(
            name="shuttleslot",
            unique_together={("shuttle", "row", "column")},
        ),
        migrations.AddIndex(
            model_name="shuttleslot",
            index=models.Index(
                fields=["shuttle", "row", "column"],
                name="shuttles_sh_shuttle_10271a_idx",
            ),
        ),
    ]
