# Generated by Django 5.2.6 on 2025-12-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttles", "0003_shuttleslot_grid_positioning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttle",
            name="description",
            field=models.TextField(
                help_text="Human-readable description (e.g., 'GF180MCU Shuttle Run 1')"
            ),
        ),
    ]
