# Generated by Django 5.2.6 on 2025-12-03 02:17

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    """Remove slot count fields that are now computed properties."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("shuttles", "0004_shuttleslot_grid_positioning"),
        # Explicit dependency: projects.0041 uses these fields in get_or_create defaults
        ("projects", "0041_populate_shuttle_and_project_ids"),
    ]

    operations: ClassVar[list[migrations.RemoveField]] = [
        migrations.RemoveField(
            model_name="shuttle",
            name="available_slots",
        ),
        migrations.RemoveField(
            model_name="shuttle",
            name="max_slots",
        ),
        migrations.RemoveField(
            model_name="shuttle",
            name="reserved_slots",
        ),
    ]
