# Generated by Django 5.2.6 on 2025-12-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttles", "0004_shuttleslot_grid_positioning"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shuttle",
            name="available_slots",
        ),
        migrations.RemoveField(
            model_name="shuttle",
            name="max_slots",
        ),
        migrations.RemoveField(
            model_name="shuttle",
            name="reserved_slots",
        ),
    ]
