# Generated by Django 5.2.6 on 2025-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttles", "0005_remove_shuttle_available_slots_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttleslot",
            name="slot_size",
            field=models.CharField(
                choices=[
                    ("1x1", "1×1"),
                    ("0p5x1", "0.5×1"),
                    ("1x0p5", "1×0.5"),
                    ("0p5x0p5", "0.5×0.5"),
                ],
                default="1x1",
                help_text="Physical size of this grid cell",
                max_length=20,
            ),
        ),
    ]
