# Generated by Django 5.2.6 on 2025-12-03 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttles", "0006_alter_shuttleslot_slot_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttleslot",
            name="column",
            field=models.PositiveIntegerField(
                default=0, help_text="Grid column index (0-based)"
            ),
        ),
        migrations.AlterField(
            model_name="shuttleslot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shuttleslot",
            name="row",
            field=models.PositiveIntegerField(
                default=0, help_text="Grid row index (0-based)"
            ),
        ),
        migrations.AlterField(
            model_name="shuttleslot",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
