# Generated by Django 5.2.6 on 2026-07-03 00:13

from django.db import migrations, models

CROWD_SUPPLY_URLS = {
    "G801": "https://www.crowdsupply.com/wafer-space/gf180mcu-run-1/",
    "G802": "https://www.crowdsupply.com/wafer-space/gf180mcu-run-2/",
    "G803": "https://www.crowdsupply.com/wafer-space/gf180mcu-run-3/",
}


def set_crowd_supply_urls(apps, schema_editor):
    """Stamp CrowdSupply campaign URLs onto known shuttle runs (if present)."""
    shuttle_model = apps.get_model("shuttles", "Shuttle")
    for name, url in CROWD_SUPPLY_URLS.items():
        shuttle_model.objects.filter(name=name).update(crowd_supply_url=url)


def unset_crowd_supply_urls(apps, schema_editor):
    """Blank the seeded URLs on reverse migration."""
    shuttle_model = apps.get_model("shuttles", "Shuttle")
    shuttle_model.objects.filter(name__in=CROWD_SUPPLY_URLS).update(
        crowd_supply_url=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0007_alter_shuttleslot_fields'),
        # projects/0041 seeds the G801 shuttle; run after it so the data
        # step below finds G801 on freshly built databases.
        ("projects", "0041_populate_shuttle_and_project_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='crowd_supply_url',
            field=models.URLField(blank=True, default='', help_text='CrowdSupply campaign page for this shuttle run (optional).', verbose_name='CrowdSupply URL'),
        ),
        migrations.RunPython(set_crowd_supply_urls, unset_crowd_supply_urls),
    ]
